# Exported from Render on 2025-05-13T17:14:58Z
services:
- type: web
  name: teste
  runtime: node
  repo: https://github.com/Alexkamil77/teste
  plan: free
  region: oregon
  buildCommand: npm install
  startCommand: node server.js
  autoDeployTrigger: commit
version: "1"
